version: '3'

volumes: 
  db: {}

services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: ​postgres​
      POSTGRES_PASSWORD: ​passwd
      POSTGRES_HOST_AUTH_METHOD: "trust"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && foreman start -f Procfile.dev -p 3000"
    volumes:
      - .:/noteapp
    ports:
      - "3001:3000"
      - "35729:35729"
    depends_on:
      - db