version: '3.7'

volumes: 
  db: {}
  cache:
  # bundle:
  gem_cache:

services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: ​postgres​
      POSTGRES_PASSWORD: ​passwd
      POSTGRES_HOST_AUTH_METHOD: "trust"
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    # command: bash -c "rm -f tmp/pids/server.pid && foreman start -f Procfile.dev -p 3000"
    command: foreman start -f Procfile.dev -p 3000
    environment: 
      - SPROCKETS_CACHE=/cache
    volumes:
      - .:/noteapp
      - cache:/cache
      # - bundle:/bundle
      - gem_cache:/usr/local/bundle/gems
    tmpfs: /noteapp/tmp/pids/
    ports:
      - "3001:3000"
      - "35729:35729"
    depends_on:
      - db